### ISSUE TITLE
Image count incorrect

### ISSUE THREAD

**Issue by dustin-lennon** [anodyne/nova#222]
The number of uploaded images: http://nova.stelth2000inc.com/screensnips/uploadedimages.png
What is displayed after clicking 'See All Imags' on character page: http://nova.stelth2000inc.com/screensnips/seeallimages.png

**Comment by agentphoenix** [comment]
Fixed in bbed8bbcc5eb8ee32af408323a853c1a1d188aa2 back in Feburary. You're either running a very old version of Nova, have a seamless substitution "bug" going on, or the updates haven't taken. Make sure you're up and running on 2.1.3.

**Comment by dustin-lennon** [comment]
Ok, was one I missed when keeping my Mods updated

**Comment by agentphoenix** [comment]
For testing your MODs, I'd make sure you're pulling directly from `2.1/master` at least, maybe even `2.1/develop` so that you know your stuff is working on the bleeding edge (unless you're purposefully maintaining compatibility with older versions).

I have my personal sim running off of a direct pull from Github so that whenever an update is released, I can just go to the command line and run `git pull origin 2.1/master` and it'll update the files necessary. Pretty easy to get something like that set up actually.

**Comment by dustin-lennon** [comment]
I updated those 2 files in that commit yet am still seeing 4 images instead of the 3, there anything I should do after updating those 2 files to correct the count?

**Comment by agentphoenix** [comment]
My guess is you're using seamless substitution on that file which is why you aren't seeing the changes. I'm running a vanilla version of 2.1.3 on my sim and don't have the issue.

**Comment by dustin-lennon** [comment]
Yeah, I'm using seamless substitution and the character function in the personnel.php is just a minor change to the function. The rest of the code is the same from the original nova_personnel.php

**Comment by agentphoenix** [comment]
I'm not talking about overriding classes, I'm talking about view files. If you're replacing that view file with seamless substitution, that would be why you're still seeing the problem still. If that doesn't fix it, delete the `nova` directory and upload a fresh copy.

**Comment by dustin-lennon** [comment]
This is what I have https://gist.github.com/4043579

**Comment by agentphoenix** [comment]
Like I said, it's all about the view file. You're obviously overriding that file either in the skin or in the `_base_override` because I'm looking at your source code on the server and it's using the old code, not the code from the commit I mentioned.

**Comment by dustin-lennon** [comment]
That's right, I forgot I was modifying the personnel_character.php from the beta skin that doesn't have the fix in it.

**Comment by agentphoenix** [comment]
Seamless substitution strikes again!

It can be your best friend and worst enemy at the same time. :P

**Comment by dustin-lennon** [comment]
Yeah it has. I'm now actually modifying the beta skin personnel_character.php and not getting the count right still. http://sto.ucip.org/personnel/character/1#prettyPhoto still is giving me 4 instead of 3

**Comment by agentphoenix** [comment]
I'm looking at the source code and it's _still_ the old code.

**Comment by dustin-lennon** [comment]
what is it i need to get changed?

**Comment by agentphoenix** [comment]
You still have something that's overriding the fixed core files you put up there.

**Comment by dustin-lennon** [comment]
what is the evidence of the old code so I know what I'm looking for?

**Comment by agentphoenix** [comment]
All of the character images should be in an unordered list, not in divs and paragraph tags.
